#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'tpope/vim-pathogen'
hook_source = 'execute pathogen#infect()'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/.config/nvim/plugins/quickrun.vim
'''

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'miyakogi/Seiya.vim'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'bfrg/vim-cpp-modern'
hook_add = '''
let g:cpp_no_function_highlight = 1
let g:cpp_simple_highlight = 1
let g:cpp_named_requirements_highlight = 1
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.nvim
'''
#
#[[plugins]]
#repo = "LumaKernel/coquille"
#

# debugger
[[plugins]]
repo = 'dbgx/lldb.nvim'
hook_add = '''
source ~/.config/nvim/plugins/lldb.nvim
'''

[[plugins]]
repo = 'puremourning/vimspector'
build = './install_gadget.py --all --force-enable-go'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
source ~/.config/nvim/plugins/syntastic.vim
 '''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
source ~/.config/nvim/plugins/fzfvim.vim
'''

#[[plugins]]
#repo = 'luochen1990/rainbow'
#hook_add = '''
#source ~/.config/nvim/plugins/rainbow.vim
#'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'iberianpig/ranger-explorer.vim'
hook_add = '''
nnoremap <Space>n :RangerOpenCurrentDir<CR>
'''

[[plugins]]
repo = 'rbgrouleff/bclose.vim'
