[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-pathogen'
hook_source = 'execute pathogen#infect()'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/.config/nvim/plugins/quickrun.vim
'''

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'miyakogi/Seiya.vim'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

#[[plugins]]
#repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
depends = ['deoplete.nvim']
hook_add = '''
source ~/.config/nvim/plugins/LanguageClient-neovim.rc.vim
'''

#[[plugins]]
#repo = 'neoclide/coc.nvim'
#rev = 'release'
#hook_add = '''
#source ~/.config/nvim/plugins/coc.vim
#'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
source ~/.config/nvim/plugins/syntastic.vim
 '''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
source ~/.config/nvim/plugins/fzfvim.vim
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
source ~/.config/nvim/plugins/rainbow.vim
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'iberianpig/ranger-explorer.vim'
hook_add = '''
nnoremap <Space>n :RangerOpenCurrentDir<CR>
'''

[[plugins]]
repo = 'rbgrouleff/bclose.vim'
