[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'Shougo/denite.nvim'
on_event = 'BufNewFile'
hook_source = 'source ~/.config/nvim/plugins/denite.rc.vim'
hook_add = 'source ~/.config/nvim/plugins/denite.vim'

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'
[[plugins]]
repo = 'neoclide/denite-git'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_source = 'denite.nvim'
hook_add = '''
  " nnoremap <silent> [Space]s :<C-u>Deol zsh -edit<CR>
  nnoremap <silent> [Window]D  :<C-u>call deol#kill_editor()<CR>
'''
hook_source = '''
  let g:deol#prompt_pattern = '%'
'''

# [[plugins]]
# repo = 'Shougo/junkfile.vim'
# on_source = 'denite.nvim'
# hook_add = '''
#   nnoremap <silent> [Window]e :<C-u>Denite junkfile:new junkfile<CR>
# '''

#[[plugins]]
#repo = "OmniSharp/omnisharp-vim"
#on_ft = ["cs"]
#build = "xbuild server/OmniSharp.sln"

[[plugins]]
repo = "cespare/vim-toml"
on_ft = ["toml"]

[[plugins]]
repo = "rhysd/vim-llvm"
on_ft = ["llvm"]
hook_source = '''
let g:llvm_extends_official = 0
'''
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
let g:rustfmt_autosave = 1
'''

#[[plugins]]
#repo = 'lervag/vimtex'
#on_ft = 'tex'
#hook_source = '''
#let g:vimtex_fold_envs = 0
#let g:vimtex_view_general_viewer = 'evince'
#'''

[[plugins]]
repo = 'vim-latex/vim-latex'
hook_add = '''
source ~/.config/nvim/plugins/vim-latex.vim
'''
on_ft = 'tex'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'aitjcize/cppman'
on_ft = 'cpp'


#[[plugins]]
## neosnippet
#repo = 'Shougo/neosnippet.vim'
#hook_source = '''
#  if has('conceal')
#    set conceallevel=2 concealcursor=niv
#  endif
#  let g:neosnippet#snippets_directory='~/.config/nvim/snippets/'
#'''
#on_i  = 1
#on_ft = ['snippet']
#depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

#[[plugins]]
#repo = 'kannokanno/previm'
#on_ft = 'markdown'

[[plugins]]
repo = 'sebwink/previm'
on_ft = 'markdown'

# debugger
[[plugins]]
repo = 'dbgx/lldb.nvim'
on_ft = ["cpp","c","py"]
hook_add = '''
source ~/.config/nvim/plugins/lldb.nvim
'''

[[plugins]]
repo = 'puremourning/vimspector'
build = './install_gadget.py --all --force-enable-go'
